### ISSUE TITLE
Incorrect instructions for example README.md

### ISSUE THREAD

**Issue by blakedietz** [loktar00/react-lazy-load#50]
You currently have the following for https://github.com/loktar00/react-lazy-load/blob/master/examples/basic/README.md

```bash
git clone https://github.com/loktar00/react-lazy-load.git

cd react-lazy-load/examples/basic
npm install
npm start

open http://localhost:3000/
```
This causes the following output for my machine : 
```bash
npm start

> react-lazy-load-basic-example@0.0.0 start /Users/blakedietz/react-lazy-load/examples/basic
> node -r 'babel-core/register' ./initializers/server/index.js

/Users/blakedietz/react-lazy-load/examples/basic/node_modules/babel-core/lib/transformation/file/options/option-manager.js:372
          throw new Error("Couldn't find preset " + JSON.stringify(val) + " relative to directory " + JSON.stringify(dirname));
          ^

Error: Couldn't find preset "es2015" relative to directory "/Users/blakedietz/react-lazy-load"
    at /Users/blakedietz/react-lazy-load/examples/basic/node_modules/babel-core/lib/transformation/file/options/option-manager.js:372:17
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/blakedietz/react-lazy-load/examples/basic/node_modules/babel-core/lib/transformation/file/options/option-manager.js:364:20)
    at OptionManager.mergePresets (/Users/blakedietz/react-lazy-load/examples/basic/node_modules/babel-core/lib/transformation/file/options/option-manager.js:348:10)
    at OptionManager.mergeOptions (/Users/blakedietz/react-lazy-load/examples/basic/node_modules/babel-core/lib/transformation/file/options/option-manager.js:307:14)
    at OptionManager.addConfig (/Users/blakedietz/react-lazy-load/examples/basic/node_modules/babel-core/lib/transformation/file/options/option-manager.js:207:10)
    at OptionManager.findConfigs (/Users/blakedietz/react-lazy-load/examples/basic/node_modules/babel-core/lib/transformation/file/options/option-manager.js:413:16)
    at OptionManager.init (/Users/blakedietz/react-lazy-load/examples/basic/node_modules/babel-core/lib/transformation/file/options/option-manager.js:461:12)
    at compile (/Users/blakedietz/react-lazy-load/examples/basic/node_modules/babel-register/lib/node.js:81:45)
    at loader (/Users/blakedietz/react-lazy-load/examples/basic/node_modules/babel-register/lib/node.js:126:14)
```
when instead it should be 

```bash
git clone https://github.com/loktar00/react-lazy-load.git

cd react-lazy-load
npm install
cd ./examples/basic
npm install
npm start

open http://localhost:3000/
```

**Comment by sergeylaptev** [comment]
@blakedietz thanks for you help!
