### ISSUE TITLE
Cannot Do Unit Test 

### ISSUE THREAD

**Issue by raliasadil** [loktar00/react-lazy-load#72]
I am getting following error when i do the test.

 ReferenceError: HTMLElement is not defined
      at scrollParent (node_modules/react-lazy-load/lib/utils/parentScroll.js:12:28)
      at LazyLoad.getEventNode (node_modules/react-lazy-load/lib/LazyLoad.js:91:14)
      at LazyLoad.componentDidMount (node_modules/react-lazy-load/lib/LazyLoad.js:56:28)
      at [object Object].invokeComponentDidMountWithTimer (node_modules/react/lib/ReactCompositeComponent.js:60:18)

as soon as i remove lazy-load component test run green

**Comment by raliasadil** [comment]
Solution is the attached Patch
From 0cfcf92b0a4929562ea0ad308603e0c7cd6954b3 Mon Sep 17 00:00:00 2001
From: "Alias Adil, Rehmatullah" <rehmatullah.alias.adil@sap.com>
Date: Thu, 8 Sep 2016 15:46:03 +0200
Subject: [PATCH] Fixes issue with HTMLElement

---
 src/utils/parentScroll.js | 2 ++
 1 file changed, 2 insertions(+)

diff --git a/src/utils/parentScroll.js b/src/utils/parentScroll.js
index e497941..4cfc154 100644
--- a/src/utils/parentScroll.js
+++ b/src/utils/parentScroll.js
@@ -3,6 +3,8 @@ const style = (element, prop) =>
     ? getComputedStyle(element, null).getPropertyValue(prop)
     : element.style[prop];
 
+var HTMLElement = typeof HTMLElement === 'undefined' ? function(){} : HTMLElement;
+
 const overflow = (element) =>
   style(element, 'overflow') + style(element, 'overflow-y') + style(element, 'overflow-x');
 
-- 
2.8.1

**Comment by ahome-tm** [comment]
Hey I want to flag this issue again. I am working with version 3.0.12. I am using mocha and enzyme testing framework. I cannot execute my unit tests for the same reason reported here. The patch suggested by @raliasadil does not work.

**Comment by RamiroIsBack** [comment]
hello,
I'm having this same Issue I think, this is the complete log while trying to run test with jest.
"react": "^16.2.0",
"react-lazy-load": "^3.0.13",
`ReferenceError: HTMLElement is not defined
      
      at scrollParent (node_modules/react-lazy-load/lib/utils/parentScroll.js:15:28)
      at LazyLoad.getEventNode (node_modules/react-lazy-load/lib/LazyLoad.js:107:41)
      at LazyLoad.componentDidMount (node_modules/react-lazy-load/lib/LazyLoad.js:71:28)
      at commitLifeCycles (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:4553:24)
      at commitAllLifeCycles (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5729:9)
      at Object.invokeGuardedCallback$1 (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:1559:10)
      at invokeGuardedCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:1506:29)
      at commitRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5833:9)
      at performWorkOnRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6800:42)
      at performWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6750:7)
`
Any progress on the matter ? thank you!!

**Comment by m8ms** [comment]
I had similar problem with `jest`. A simple mock helped:
```javascript
jest.mock('react-lazy-load', () => (props) => props.children)
```
However, I have no idea how this applies to other testing suites.

**Comment by joFolta** [comment]
@m8ms solution worked for me! Thanks!
https://jestjs.io/docs/en/mock-functions#mocking-modules
